//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;24&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-12&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoralRiff1 {
            get {
                return ResourceManager.GetString("CoralRiff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;24&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-12&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoralRiff2 {
            get {
                return ResourceManager.GetString("CoralRiff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;26&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-12&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoralRiff3 {
            get {
                return ResourceManager.GetString("CoralRiff3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;27&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-12&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoralRiff4 {
            get {
                return ResourceManager.GetString("CoralRiff4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;16&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-16&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeathMetal1 {
            get {
                return ResourceManager.GetString("DeathMetal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;17&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-16&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeathMetal2 {
            get {
                return ResourceManager.GetString("DeathMetal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;18&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-16&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeathMetal3 {
            get {
                return ResourceManager.GetString("DeathMetal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;19&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-16&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-15&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-14&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-6&quot; y=&quot;-13&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeathMetal4 {
            get {
                return ResourceManager.GetString("DeathMetal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;20&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-15&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-14&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-13&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-12&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeepBlues1 {
            get {
                return ResourceManager.GetString("DeepBlues1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;21&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-15&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-14&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-13&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-12&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeepBlues2 {
            get {
                return ResourceManager.GetString("DeepBlues2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;22&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-15&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-14&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-13&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-12&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeepBlues3 {
            get {
                return ResourceManager.GetString("DeepBlues3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;23&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-15&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-14&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-13&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-4&quot; y=&quot;-12&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeepBlues4 {
            get {
                return ResourceManager.GetString("DeepBlues4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;MY DUNGEON&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;-1&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;100&quot; x=&quot;-6&quot; y=&quot;-6&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;100&quot; x=&quot;-6&quot; y=&quot;-5&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;100&quot; x=&quot;-6&quot; y=&quot;-4&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;1&quot; type=&quot;100&quot; x=&quot;-6&quot; y=&quot;-3&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;100&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;12&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-18&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-17&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-16&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-15&quot; zone=&quot;0&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingConga1 {
            get {
                return ResourceManager.GetString("KingConga1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;13&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-18&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-17&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-16&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-15&quot; zone=&quot;1&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingConga2 {
            get {
                return ResourceManager.GetString("KingConga2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;14&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-18&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-17&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-16&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-15&quot; zone=&quot;2&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingConga3 {
            get {
                return ResourceManager.GetString("KingConga3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;
        ///&lt;dungeon character=&quot;-1&quot; name=&quot;BOSSES&quot; numLevels=&quot;1&quot;&gt;
        ///    &lt;level bossNum=&quot;15&quot; music=&quot;0&quot; num=&quot;1&quot;&gt;
        ///        &lt;tiles&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-18&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-17&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-16&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x=&quot;-8&quot; y=&quot;-15&quot; zone=&quot;4&quot;&gt;&lt;/tile&gt;
        ///            &lt;tile cracked=&quot;0&quot; torch=&quot;0&quot; type=&quot;109&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KingConga4 {
            get {
                return ResourceManager.GetString("KingConga4", resourceCulture);
            }
        }
    }
}
