version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: toofz.NecroDancer.Web.sln
  verbosity: minimal
