version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
build:
  project: toofz.NecroDancer.Web.sln
  publish_wap: true
  verbosity: minimal
cache:
  - packages -> **\packages.config
  - '%APPDATA%\npm-cache'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 8)
  - npm install --global npm
  - node --version
  - npm --version
before_build:
  - nuget restore
  - cd toofz.NecroDancer.WebClient
  - npm install
  - npm run build
  - cd ..

test_script:
  - vstest.console /logger:Appveyor "SqlBulkUpsert.Tests\bin\Release\SqlBulkUpsert.Tests.dll"
  - vstest.console /logger:Appveyor "toofz.NecroDancer.Tests\bin\%CONFIGURATION%\toofz.NecroDancer.Tests.dll"
  - vstest.console /logger:Appveyor "toofz.NecroDancer.Leaderboards.Tests\bin\%CONFIGURATION%\toofz.NecroDancer.Leaderboards.Tests.dll"
  - vstest.console /logger:Appveyor "toofz.NecroDancer.Web.Api.Tests\bin\%CONFIGURATION%\toofz.NecroDancer.Web.Api.Tests.dll"
  - cd toofz.NecroDancer.WebClient
  - npm test
  - cd ..
