//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Leaderboards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Leaderboards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;leaderboards&quot;: [
        ///    {
        ///      &quot;id&quot;: 391760,
        ///      &quot;product&quot;: &quot;Classic&quot;,
        ///      &quot;date&quot;: &quot;2014-07-30T00:00:00Z&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 394529,
        ///      &quot;product&quot;: &quot;Classic&quot;,
        ///      &quot;date&quot;: &quot;2014-07-31T00:00:00Z&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 396523,
        ///      &quot;product&quot;: &quot;Classic&quot;,
        ///      &quot;date&quot;: &quot;2014-08-01T00:00:00Z&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 396524,
        ///      &quot;product&quot;: &quot;Classic&quot;,
        ///      &quot;date&quot;: &quot;2014-08-02T00:00:00Z&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 396525,
        ///      &quot;product&quot;: &quot;Classic&quot;,
        ///      &quot;date&quot;: &quot;2014 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DailyLeaderboardHeaders {
            get {
                return ResourceManager.GetString("DailyLeaderboardHeaders", resourceCulture);
            }
        }
    }
}
